version: '3.3'

services: 
  app-db:
    image: mysql:5.7
    container_name: magalu-mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    networks:
      - magalu-network

  app-service:
    container_name: magalu-app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: magalu-app
    depends_on:
      - app-db
    stdin_open: true
    tty: true
    networks:
      - magalu-network

networks: 
  magalu-network:
    driver: bridge