version: '2.2'

services: 
  mysqldb:
    container_name: magalu-mysql
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    networks:
      - mysql-compose-network

  #adminer:
  #  image: adminer
  #  ports:
  #    - 8080:8080
  #  networks:
  #    - mysql-compose-network

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: magalu-app
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

networks: 
  mysql-compose-network:
    driver: bridge