version: '2.2'

services: 
  mysqldb:
    container_name: magalu-mysql
    image: mysql:5.7
    restart: always
    env_file: ./.env
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    networks:
      - magalu-network

  app:
    container_name: magalu-app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: magalu-app
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    networks:
      - magalu-network

networks: 
  magalu-network:
    driver: bridge